//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TP_PSI.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PSIEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PSIEntities object using the connection string found in the 'PSIEntities' section of the application configuration file.
        /// </summary>
        public PSIEntities() : base("name=PSIEntities", "PSIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PSIEntities object.
        /// </summary>
        public PSIEntities(string connectionString) : base(connectionString, "PSIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PSIEntities object.
        /// </summary>
        public PSIEntities(EntityConnection connection) : base(connection, "PSIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hospital> Hospital
        {
            get
            {
                if ((_Hospital == null))
                {
                    _Hospital = base.CreateObjectSet<Hospital>("Hospital");
                }
                return _Hospital;
            }
        }
        private ObjectSet<Hospital> _Hospital;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Medico> Medico
        {
            get
            {
                if ((_Medico == null))
                {
                    _Medico = base.CreateObjectSet<Medico>("Medico");
                }
                return _Medico;
            }
        }
        private ObjectSet<Medico> _Medico;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hospital EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHospital(Hospital hospital)
        {
            base.AddObject("Hospital", hospital);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Medico EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedico(Medico medico)
        {
            base.AddObject("Medico", medico);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSIModel", Name="Hospital")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hospital : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hospital object.
        /// </summary>
        /// <param name="hospitalId">Initial value of the HospitalId property.</param>
        public static Hospital CreateHospital(global::System.Int32 hospitalId)
        {
            Hospital hospital = new Hospital();
            hospital.HospitalId = hospitalId;
            return hospital;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HospitalId
        {
            get
            {
                return _HospitalId;
            }
            set
            {
                if (_HospitalId != value)
                {
                    OnHospitalIdChanging(value);
                    ReportPropertyChanging("HospitalId");
                    _HospitalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HospitalId");
                    OnHospitalIdChanged();
                }
            }
        }
        private global::System.Int32 _HospitalId;
        partial void OnHospitalIdChanging(global::System.Int32 value);
        partial void OnHospitalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomHosp
        {
            get
            {
                return _NomHosp;
            }
            set
            {
                OnNomHospChanging(value);
                ReportPropertyChanging("NomHosp");
                _NomHosp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomHosp");
                OnNomHospChanged();
            }
        }
        private global::System.String _NomHosp;
        partial void OnNomHospChanging(global::System.String value);
        partial void OnNomHospChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ender
        {
            get
            {
                return _Ender;
            }
            set
            {
                OnEnderChanging(value);
                ReportPropertyChanging("Ender");
                _Ender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ender");
                OnEnderChanged();
            }
        }
        private global::System.String _Ender;
        partial void OnEnderChanging(global::System.String value);
        partial void OnEnderChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSIModel", Name="Medico")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medico : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Medico object.
        /// </summary>
        /// <param name="codMed">Initial value of the CodMed property.</param>
        public static Medico CreateMedico(global::System.Int32 codMed)
        {
            Medico medico = new Medico();
            medico.CodMed = codMed;
            return medico;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodMed
        {
            get
            {
                return _CodMed;
            }
            set
            {
                if (_CodMed != value)
                {
                    OnCodMedChanging(value);
                    ReportPropertyChanging("CodMed");
                    _CodMed = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodMed");
                    OnCodMedChanged();
                }
            }
        }
        private global::System.Int32 _CodMed;
        partial void OnCodMedChanging(global::System.Int32 value);
        partial void OnCodMedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomMed
        {
            get
            {
                return _NomMed;
            }
            set
            {
                OnNomMedChanging(value);
                ReportPropertyChanging("NomMed");
                _NomMed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomMed");
                OnNomMedChanged();
            }
        }
        private global::System.String _NomMed;
        partial void OnNomMedChanging(global::System.String value);
        partial void OnNomMedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DcrEspec
        {
            get
            {
                return _DcrEspec;
            }
            set
            {
                OnDcrEspecChanging(value);
                ReportPropertyChanging("DcrEspec");
                _DcrEspec = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DcrEspec");
                OnDcrEspecChanged();
            }
        }
        private global::System.String _DcrEspec;
        partial void OnDcrEspecChanging(global::System.String value);
        partial void OnDcrEspecChanged();

        #endregion
    
    }

    #endregion
    
}
