//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TP_PSI.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PSIEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PSIEntities1 object using the connection string found in the 'PSIEntities1' section of the application configuration file.
        /// </summary>
        public PSIEntities1() : base("name=PSIEntities1", "PSIEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PSIEntities1 object.
        /// </summary>
        public PSIEntities1(string connectionString) : base(connectionString, "PSIEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PSIEntities1 object.
        /// </summary>
        public PSIEntities1(EntityConnection connection) : base(connection, "PSIEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hospital> Hospital
        {
            get
            {
                if ((_Hospital == null))
                {
                    _Hospital = base.CreateObjectSet<Hospital>("Hospital");
                }
                return _Hospital;
            }
        }
        private ObjectSet<Hospital> _Hospital;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hospital EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHospital(Hospital hospital)
        {
            base.AddObject("Hospital", hospital);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSIModel1", Name="Hospital")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hospital : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hospital object.
        /// </summary>
        /// <param name="codHosp">Initial value of the CodHosp property.</param>
        public static Hospital CreateHospital(global::System.Int32 codHosp)
        {
            Hospital hospital = new Hospital();
            hospital.CodHosp = codHosp;
            return hospital;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodHosp
        {
            get
            {
                return _CodHosp;
            }
            set
            {
                if (_CodHosp != value)
                {
                    OnCodHospChanging(value);
                    ReportPropertyChanging("CodHosp");
                    _CodHosp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodHosp");
                    OnCodHospChanged();
                }
            }
        }
        private global::System.Int32 _CodHosp;
        partial void OnCodHospChanging(global::System.Int32 value);
        partial void OnCodHospChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomHosp
        {
            get
            {
                return _NomHosp;
            }
            set
            {
                OnNomHospChanging(value);
                ReportPropertyChanging("NomHosp");
                _NomHosp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomHosp");
                OnNomHospChanged();
            }
        }
        private global::System.String _NomHosp;
        partial void OnNomHospChanging(global::System.String value);
        partial void OnNomHospChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ender
        {
            get
            {
                return _Ender;
            }
            set
            {
                OnEnderChanging(value);
                ReportPropertyChanging("Ender");
                _Ender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ender");
                OnEnderChanged();
            }
        }
        private global::System.String _Ender;
        partial void OnEnderChanging(global::System.String value);
        partial void OnEnderChanged();

        #endregion
    
    }

    #endregion
    
}
